language: python
python:
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install ."
# command to run tests
script: nosetests