language: python
python:
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install python-coveralls"
  - "pip install ."

before_script:
  - mysql -e 'create database cgd_test;'
  - mysql -u travis -D cgd_test < resources/g2p.sql.gz

# command to run tests
script: nosetests --with-coverage --cover-package=mckb

after_success:
  coveralls

# whitelist
branches:
  only:
    - master